export default {
  font: {
    light: 300,
    normal: 400,
    bold: 600,
    sizes: {
      xsmall: '18px',
      small: '20px',
      medium: '22px',
      large: '24px',
      xlarge: '28px',
      xxlarge: '36px',
      huge: '44px',
    },
  },
  colors: {
    primary: '#054A91',
    secondary: '#fbf1e5',
    mainBg: '#06092B',
    lightBg: '#F2F2F2',
    white: '#FAFAFA',
    black: '#030517',
    lightGray: '#EAEAEA',
    gray: '#8F8F8F',
    darkGray: '#2E2F42',
    red: '#FF6347',
    lightOrange: '#DBE4EE',
    lightBlue: '#6DBEC5',
  },
  spacings: {
    xxsmall: '4px',
    xsmall: '6px',
    small: '12px',
    medium: '16px',
    large: '20px',
    xlarge: '34px',
    xxlarge: '50px',
  },
} as const;
