export default {
  font: {
    light: 300,
    normal: 400,
    bold: 600,
    sizes: {
      xsmall: '18px',
      small: '20px',
      medium: '22px',
      large: '24px',
      xlarge: '28px',
      xxlarge: '30px',
      huge: '44px',
    },
  },
  colors: {
    primary: '#054A91',
    secondary: '#3CD3C1',
    mainBg: '#06092B',
    lightBg: '#F2F2F2',
    white: '#FAFAFA',
    black: '#030517',
    lightGray: '#EAEAEA',
    gray: '#8F8F8F',
    darkGray: '#2E2F42',
    red: '#FF6347',
    lightOrange: '#DBE4EE',
    lightBlue: '#6DBEC5',
  },
  spacings: {
    xxsmall: '0.8rem',
    xsmall: '1.6rem',
    small: '2.4rem',
    medium: '3.2rem',
    large: '4.0rem',
    xlarge: '4.8rem',
    xxlarge: '5.6rem',
  },
} as const;
